### ISSUE TITLE
Status check for pipeline checkpoints

### ISSUE THREAD

**Issue by vreuter** [pepkit/pep#187]
For samples being processed by `pypiper` pipeline(s), it'd be nice to be able to have a `check` or `status` like mechanism to be able to see for a project's collection of samples the distribution of current processing states and ones completed. See https://github.com/epigen/pypiper/issues/56

**Comment by nsheff** [comment]
this is basically what `looper check` does, right? Or are you suggesting something else? Just showing the %? Could it just be added to the end of `looper check` ?

**Comment by vreuter** [comment]
`check` looks at flags that I'd classify as both status and health related, with more coarse status signal. This would not relate to health, but pipeline stage, e.g. whether a sample has completed the `trim_reads` stage, `align_reads` stage, etc.
