### ISSUE TITLE
License feedback

### ISSUE THREAD

**Issue by nsheff** [pepkit/pep#202]
PEP/looper lack licenses at the moment. I would like to propose we use the BSD-2 license, but wanted to open it up for discussion in case there is any strong opinion otherwise.

**Comment by vreuter** [comment]
If the same principles apply as we discussed in a lab meeting a while back, I'd lean toward GPL, but certainly not strongly. Nothing but weak, tepid opinion here.

**Comment by afrendeiro** [comment]
My default is either GPL or MIT. Do you prefer BSD2 because iit requires attribution when copying or redistributing? I don't have any strong preference.

**Comment by nsheff** [comment]
See [this post](http://ivory.idyll.org/blog/2015-on-licensing-in-bioinformatics.html) for some rationale on choosing BSD.

**Comment by vreuter** [comment]
I think @nsheff chose BSD, closing for now.
